Feature/add ncc (#2)
* add husky

* add build step to checkin action

* add pre-push script to check for build

* fix the pre-push script extension

* remove ts test file

* fix jest config

* replace npm ci with normal install

* add npm ci to pre-push

* add pre-commit hook

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -10,6 +10,9 @@ jobs:
     - name: "npm ci"
       run: npm ci
 
+    - name: "npm run build"
+      run: npm run build
+
     - name: "npm run test"
       run: npm run test
 
@@ -17,6 +20,6 @@ jobs:
       # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
       run: |
         git diff --exit-code --stat -- . ':!node_modules' \
-        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
-                 "and check in all changes" \
+        || (echo "##[error] found changed files after build. please 'npm run build'" \
+                  "and check in all changes" \
             && exit 1)
